---
title: 'Part A: Insert CSV Data Into Aiven DB'
author: 'SioWa Luo'
date: 'Summer 2025'
output: html_notebook
---

## Part A
```{r connectToAivenDB, echo=FALSE}
# Import Necessary Library
library(RMySQL)
library(DBI)

# Define Setting
db_host_aiven <- "mysql-cs3200-northeastern-cs3200.k.aivencloud.com"
db_port_aiven <- 22967
db_name_aiven <- "defaultdb"
db_user_aiven <- "avnadmin"
db_pwd_aiven <- "AVNS_b8LFfIb2ijYwEuui_FU"

# Embedded SSL certificate
db_cert <- 
"
-----BEGIN CERTIFICATE-----
MIIEUDCCArigAwIBAgIUDSsZAl6kvMb0yrAdHFvhOPbcJ70wDQYJKoZIhvcNAQEM
BQAwQDE+MDwGA1UEAww1YzNiYTJlNTMtNDA5NS00YjM3LWEwYmUtNDllODgwODBl
ODI4IEdFTiAxIFByb2plY3QgQ0EwHhcNMjUwODAzMjE0NDEzWhcNMzUwODAxMjE0
NDEzWjBAMT4wPAYDVQQDDDVjM2JhMmU1My00MDk1LTRiMzctYTBiZS00OWU4ODA4
MGU4MjggR0VOIDEgUHJvamVjdCBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCC
AYoCggGBAL5qvx5moiDVHp44nyhjUIeYz9naW7pVPqb9ZSF+USu2IXh4zjFH24Js
hxCu/kdALiQfcgjWUisBnPmguuV+GCTqEYrmfIpD7tEmp5Zls1s4eWL4YtNYMO9p
mhHaR/mKFA9+AmDDLB13sO2+IgJxvEjDXkdDHbTnHwPgX1pUBo+d0evTZhcoqpRz
UiqvsT2pyUb8FsRH83DReyM4qaV8EzOEjM8wIZEvO29Wn6cxcRxADE7Cn1I6k3Q9
rheEYNIzU3d+vrwdQQg+fc7qTmYr6swnU7fNOGawHufkHjaXiZJZk0jztVnp/m/G
3BfenTy+UWEa3CIk5l80LRJ/QHO+kCXnlunkW5ky7DkRulcXcT30R1qF5OzQQYC1
gL4lHrd9HG6yR++3CWzwt9AxSrmbzDL2Y56wZjtJcKfNiSeHIIWZ7y1gnFHzGyJT
QTDXvETAVdNIrLbjuRWrjp11l1x4w6TgWsKoi/1sY7Wr4r+oga+UNLiQhpJJy94J
AroefkBNZwIDAQABo0IwQDAdBgNVHQ4EFgQU7X6M21DSCxWu/lDNUDII1del8YIw
EgYDVR0TAQH/BAgwBgEB/wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQAD
ggGBAL2gxg4vYo4MVQPujzOTmrAKuRlG0uT3gwgKfyCTNbPrlQE/ux0aYdg7ZcQg
LBjHqxTJMsq7Lo/Y1c8DvqtBEcSFTfJ3A/HRJj9I5Wkuj9AzGdXX/J9RH9xdzIEU
bqxap847vC8ddrBHGD7E5K6tilRzsZe412I+ymVPylM0mDJm9YOihojfhqlBGDYR
9qDYFWcbnwsHrna/qIywLtZrJMs4xOX+Oz8LPdqGZ1+TPEahEUl6WxH0ivggorFw
lx69r+wQN6x/ETrbXLj5AkwUo0LcQi/RXN5Vis9VQcVtWUrz6Tt96k0q8x1WsR7M
93lnSusJEOn7d8NhuQ7iZdGv4qy7h1J92iWVxswYvAV15AmOOzmuFlQxBfkviFH/
KCq03oic8tsZadXAtapY4MHo6dqtHQw1Zc1e27+X4p2qOzwBK94UQlhUeTCrALXq
187ebDb5S0ZRCvxBTgzThxgfgg00jcjNr+wxkQBzf5xPkpy4nQ9qtEndZ4zJOTgh
Ac412g==
-----END CERTIFICATE-----
"

# connect to remote MySQL server and database
mydb.aiven <-  dbConnect(RMySQL::MySQL(), 
                         user = db_user_aiven, 
                         password = db_pwd_aiven,
                         dbname = db_name_aiven, 
                         host = db_host_aiven, 
                         port = db_port_aiven,
                         sslmode = "require",
                         sslcert = db_cert)
```

```{r cleanData, echo=FALSE}
# Load data using url
url <- "https://s3.us-east-2.amazonaws.com/artificium.us/datasets/incidents-v2.csv"
incidents_data <- read.csv(url, header = T, stringsAsFactors = F)

# Filter column we need
incidents_data <- incidents_data[, c("iid", "date", "airline", "flightNumber", 
                          "dep.airport", "incidentType", "severity", 
                          "delay", "num.injuries", "reported.by", "aircraft")]

# Change date format to match mysql
incidents_data$date <- as.Date(incidents_data$date, format = "%d.%m.%Y")

# Load cleaned data sample
head(incidents_data, 50)
```
```{r createDatabaseTable, echo=FALSE}
# Drop table if it exists so that we can rerun it
dbExecute(mydb.aiven, "DROP TABLE IF EXISTS incidents")

# Create table in db
create_table_query <- paste0(
    "CREATE TABLE incidents (",
    "iid VARCHAR(50) PRIMARY KEY,",
    "incident_date DATE,",
    "airline VARCHAR(100),",
    "flightNumber INT,",
    "dep_airport VARCHAR(10),",
    "incidentType VARCHAR(100),",
    "severity VARCHAR(50),",
    "delay_minutes INT,",
    "num_injuries INT,",
    "reported_by VARCHAR(100),",
    "aircraft VARCHAR(100)",
    ")"
)

dbExecute(mydb.aiven, create_table_query)
```

```{r insertDataFunction, echo=FALSE}
# Function 1: Convert one row of data to SQL format
convert_format <- function(row_data) {
    iid <- paste0("'", row_data$iid, "'")
    date_val <- paste0("'", row_data$date, "'")
    airline <- paste0("'", row_data$airline, "'")
    flight_num <- row_data$flightNumber
    airport <- paste0("'", row_data$dep.airport, "'")
    incident <- paste0("'", row_data$incidentType, "'")
    severity <- paste0("'", row_data$severity, "'")
    delay <- row_data$delay
    injuries <- row_data$num.injuries
    reported <- paste0("'", row_data$reported.by, "'")
    aircraft <- paste0("'", row_data$aircraft, "'")
    
    # Return one row in SQL format
    paste0("(", iid, ",", date_val, ",", airline, ",", flight_num, ",", 
           airport, ",", incident, ",", severity, ",", delay, ",", 
           injuries, ",", reported, ",", aircraft, ")")
}

# Function 2: Insert rows into DB
insert_data <- function(data_rows) {
    # Convert each row to SQL format
    sql_rows <- ""
    for (i in 1:nrow(data_rows)) {
        one_row <- convert_format(data_rows[i, ])
        
        if (i == 1) {
            db_rows <- one_row
        } else {
            db_rows <- paste0(db_rows, ",", one_row)
        }
    }
    
    # Create and execute the INSERT statement
    insert_query <- paste0("INSERT INTO incidents VALUES ", db_rows)
    dbExecute(mydb.aiven, insert_query)

}
```
```{r insertDataToDB, echo=FALSE}
total_rows <- nrow(incidents_data)
batch_size <- 500

cat("Starting to load", total_rows, "rows in batches of", batch_size, "\n")

# Process all data in batches of 500
for (i in seq(1, total_rows, batch_size)) {
    # Calculate end row for this batch
    end_row <- min(i + batch_size - 1, total_rows)
    
    # Get the current batch of data
    current_batch <- incidents_data[i:end_row, ]
    
    # Insert this batch using your function
    insert_data(current_batch)
}


dbDisconnect(mydb.aiven)
```




